### ISSUE TITLE
Helper links to edit markdown files not working 

### ISSUE THREAD

**Issue by maxulysse** [nf-core/nf-co.re#1146]
Former pages in `/docs` are not properly listed anymore:

```
 Read this page on GitHub: https://github.com/nf-core/nf-co.re/tree/master/markdown/docs/usage/nextflow.md
```
 should be
```
  Read this page on GitHub: https://github.com/nf-core/nf-co.re/tree/master/markdown/usage/nextflow.md
```

**Comment by ewels** [comment]
Good catch 👍🏻  This is because of the halfway-house approach that we took so that people's PRs wouldn't get messed up during the hackthon.

We should have a run through the open PRs to make sure that there's nothing that will get messed up, then switch the folder structure: move the folders then set up `.htaccess` rules to redirect the old URLs.

**Comment by mirpedrol** [comment]
Closing as it's outdated
