### ISSUE TITLE
Page not found

### ISSUE THREAD

**Issue by hypotheses** [nf-core/nf-co.re#195]
"It looks like https://nf-co.re/developers/usage/nextflow_tutorial doesn't exist." 

![image](https://user-images.githubusercontent.com/478839/66017553-80340200-e505-11e9-876f-1e5e30aaada0.png)

I followed the link "Nextflow Tutorial" at the bottom of this page: https://nf-co.re/developers/guidelines ", and ended up here.

**Comment by ewels** [comment]
Oops, good spot! In fact, several of those links don't work properly - they're relative to the current page instead of to the site root. If you keep clicking, the URL get's more ridiculous 😅 

![image](https://user-images.githubusercontent.com/465550/66162840-61318f00-e62f-11e9-8c95-a2def882ae43.png)
