### ISSUE TITLE
Rethink nav for documentation

### ISSUE THREAD

**Issue by ewels** [nf-core/nf-co.re#352]
As the amount of documentation on the website grows, the navigation becomes more important. Some issues currently:

* The nav titles _Usage_ and _Developers_ are not obviously Documentation pages
* The distinction between _Usage_ and _Developers_ is not always super clear
* There is very little homepage real-estate given for documentation.

Suggestion:

- [ ] Move all docs into a single Nav dropdown called _Documentation_ with base URL `/docs/`
- [ ] Have a full listing page showing all documentation pages along with their subtitles for quick reference.
- [ ] Homepage: replace the block with _See what's available_ / _Run a pipeline_ / _Get into the code_ headings with a _Documentation_ section
    * Listing all docs here is probably too much. However, we could have the top-level structure shown on the left with an interactive hover / click revealing sub-pages on the right.
    * An interactive filter box could do a quick search for different documentation pages in place.
- [ ] Add redirects from old URLs to new.

As part of this, need to think about the best hierarchical structure for all documentation pages. Note that it's entirely possible that the current _Usage_ / _Developers_ breakdown is the best (I can't really think of anything better at the moment). Alternative suggestions welcome.

Phil

**Comment by mahesh-panchal** [comment]
Perhaps change Usage to New Users, and Developers to Contributing? 
Tools looks like it could go in the Developers category. 
I think the category breakdown though is good.

**Comment by ewels** [comment]
> Tools looks like it could go in the Developers category.

The reason I haven't already done this is that quite a few of the things documented there (`nf-core list`, `launch`, `download`, `licences`) are for pipeline users and not developers.

It might make sense to split this documentation up I guess. For now it just pulls the tools readme file.

**Comment by KevinMenden** [comment]
I strongly agree that 'Usage' and 'Developers' should be merged into 'Documentation', as it is clearer where to go.
I would then actually keep 'Usage', which IMO is understandable and commonly used for software usage descriptions.
Switching 'Developers' into 'Contributing' might make it more clearer though. 

Regarding tools - there the question is if you really want a separate header/section for just this? Because after all, given what it does, it is (or should be) mentioned extensively at the write places in the 'Usage' and 'Contributing/Developers' sections. Or you could put it into the documentation section:

- Documentation
    - Usage
    - Contributing
    - Tools

Either way I think the best change would be merging Usage and Developers.
For the latter, I would then suggest to add an additional one or two sections, which describe how pipeline code is structured and why and maybe also a section about the nf-core core repositories, although that's not so pressing.
Not quite sure how to name such a section, maybe 'Pipeline Design', 'Pipeline Design Principles', or something like that ....

**Comment by mashehu** [comment]
I think we need to switch perspective from a "package" view point to a "command" view point. This means for example splitting up the documentation for nf-core/tools into user-centric ones (`list`, `launch`, `download`, `licenses`) and the rest into the developer-centric docs. This means for example also splitting up the "nf-core tutorial" section. 

I am not sure if I am all for merging "Usage" and "Developers", just because they are both documentation sections. They serve a completely different audience and might confuse new-comers even more.  But I think we could merge some subsections there (merge the tutorial and data section into "User guide" and merge "Guidelines" with "Design Guidelines"). A clearer path from one documentation section to the next would also be helpful, for example is the link in the end of "Getting started" to nf-core tools docs, which is probably not where we want new users to continue. We should there either point to the nf-core-tutorial/User guide or have a pipeline selection field, because at this point you probably want to start with the pipeline you came here for at the beginning and all of them have their own tutorial anyway.

**Comment by mashehu** [comment]
But I agree with switching "Developers" to "Contributing".

**Comment by KevinMenden** [comment]
I think it' a good idea to split-up tools, like you mentioned. That would probably make it clearer how to use it, and when. 

Yes sure not entirely certain that merging it into Docs would make it clearer - but switching the name a bit would be a good idea in my opinion :-) 
For instance, bioconda has "User Docs" and "Developer Docs" on their site, which is a bit more straight forward. 

Good point also with the "Getting started" section. In theory there are several links in it and if you read it properly you should find the links to the correct site. But if you really read it to the end it would indeed be nice to have one or a few links to good next stations.

**Comment by ewels** [comment]
Yes I agree about tools. This has come up before / I've been thinking about it before, it's stayed like it is for so long because the website simply parses the nf-core/tools `README.md`. But I think that it's probably time to cut that readme right down and move stuff over to the website docs properly (it made more sense in the early days when nf-core/tools didn't do much).

Whatever structure we go for, I think what is key is that we have a multi-level hierarchical navigation. The top navbar dropdowns are no longer really sufficient for the amount of content that we have now, so I think we need a rethink of how to move around. Probably [RTD](https://www.nextflow.io/docs/latest/index.html) / [Bootstrap](https://getbootstrap.com/docs/4.5/getting-started/introduction/) style sidebars are the most obvious way to go, once under the `/docs/` section. Then perhaps a flat link in the navbar can load the title page which a lot more space for sub-pages in the secondary nav.

I quite like all the suggestions here - I think having "Docs" in the headings is a minimum requirement and already helps a lot (also a bonus is not needing to change so many URLs).

**Comment by ewels** [comment]
What do people think about mimicking the organisation / navigation of the Nextflow Tower docs? https://help.tower.nf/

I quite like having the sidebar with space for lots of links to lots of different pages, grouped into sections with headings. This could then give scope for quite a few more sections than just Usage / Developers / Tools.

**Comment by mashehu** [comment]
Okay, so basically the readthedocs layout and a `nf-core docs` button in the navbar? 
Would make it easier to make a more coherent experience. But I think we still need to communicate clearly that each pipeline has it's own documentation and that the nf-core docs contains general usage information, but also specific information for pipeline developers (whereas the nf-tower doc is mainly covering on the general usage part).

**Comment by ewels** [comment]
Yup, or just _Docs_ / _Documentation_ I think would be fine. We can put a box near the top of the main index page pointing out that pipelines are documented under _Pipelines_.

**Comment by ewels** [comment]
Ideas for extending markdown files YAML front-matter:

- Priority
- Section (for sources outside the nf-core website, eg. nf-core/tools)
- Keywords for searching

**Comment by ewels** [comment]
Nav reorganisation:

- [ ] - Rename Developers > Contributing
- [ ] - Merge Usage + Contributing under top level "Docs"
- [ ] - Remove top-level Tools link
- [ ] - Make dropdowns in the nav just "Usage" and "Contributing"
- [ ] - Build secondary sidebar nav for tertiary docs pages
- [ ]     - If possible, able to be (infinitely??) nested
- [ ]     - Model metadata on Hugo (see above)

Tools reorganisation:

- [ ] - Split out into separate MD files under `docs/`
- [ ] - Built into new nf-core nav using front-matter
