### ISSUE TITLE
Dockstore support

### ISSUE THREAD

**Issue by ewels** [nf-core/nf-co.re#65]
Hi @agduncan94, @denis-yuen,

Thanks again for the Dockstore - nextflow support! I was just poking around again and noticed that not all releases are showing up though.

For example, nf-core/rnaseq has versions `1.1` and `1.2` released now (https://github.com/nf-core/rnaseq/releases), however, the dockstore page (https://dockstore.org/workflows/github.com/nf-core/rnaseq:1.0?tab=versions) only lists `1.0` and `1.1`, and also has `1.0` listed as the default version.

There are also only 9 nf-core workflows listed, but now over 20 are present (we keep a JSON list at https://nf-co.re/pipelines.json if it helps).

Is there anything we can do to help all releases be pulled into Dockstore? Would it be possible to have the latest release set as the default version for all nf-core pipelines?

Cheers,

Phil

**Comment by agduncan94** [comment]
Hey @ewels ,

Currently with Dockstore you need to manually pull changes made on GitHub. You can do this by using the Refresh Organisation button found on the My Workflows page for github.com/nf-core. Since the workflow has not been refreshed since the 1.2 release, 1.2 will not show up.

Any time new workflows are added to the nf-core organisation on GitHub, Dockstore needs to be told about them. To do this you can again select the Refresh Organisation on the My Workflows page for github.com/nf-core. This will fetch new workflows as stubs, since it pulls all repos in a GitHub organisation and we can't easily tell which are actual Dockstore workflows. Individually refreshing a workflow after setting the metadata will pull the Nextflow files onto Dockstore. The workflow can be published assuming there is at least one valid version.

Note something like webhooks are on the roadmap for the future so that this becomes more automated.

Unfortunately there is no way currently to automatically set the latest release as the default version, though I think this could be a useful feature and will create an issue for discussion on the Dockstore Github page.

I will update the existing workflows and add the new ones now.

**Comment by ewels** [comment]
Great stuff, thanks for the info 👍 Would it be possible to add me to the nf-core organisation on Dockstore? I don't have access to those pages currently. I just logged in with GitHub so my dockstore username is now `ewels`.

Phil

**Comment by agduncan94** [comment]
Hey @ewels , if you have access to the nf-core on GitHub then you should have access on Dockstore, however you must do a refresh all to see them. Go to the [My Workflows](https://dockstore.org/my-workflows) page and click the Refresh All button on the top left. You should see the organisation github.com/nf-core. Here you can pull new content and also update metadata (ex. labels).

**Comment by ewels** [comment]
Great stuff, thank you for the help! 👍
